--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-04-21 10:03:15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3808 (class 1262 OID 14174)
-- Name: postgres; Type: DATABASE; Schema: -; Owner: sgpostgres
--

CREATE DATABASE postgres WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE postgres OWNER TO sgpostgres;

\connect postgres

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3809 (class 0 OID 0)
-- Dependencies: 3808
-- Name: DATABASE postgres; Type: COMMENT; Schema: -; Owner: sgpostgres
--

COMMENT ON DATABASE postgres IS 'default administrative connection database';


--
-- TOC entry 5 (class 2615 OID 16394)
-- Name: users; Type: SCHEMA; Schema: -; Owner: sgpostgres
--

CREATE SCHEMA users;


ALTER SCHEMA users OWNER TO sgpostgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 16444)
-- Name: kodexuser; Type: TABLE; Schema: users; Owner: sgpostgres
--

CREATE TABLE users.kodexuser (
    id smallint NOT NULL,
    namedisplay character varying NOT NULL,
    namefull character varying NOT NULL,
    goodreadsuserid character varying,
    goodreadsurl character varying
);


ALTER TABLE users.kodexuser OWNER TO sgpostgres;

--
-- TOC entry 203 (class 1259 OID 16442)
-- Name: kodexuser_id_seq; Type: SEQUENCE; Schema: users; Owner: sgpostgres
--

ALTER TABLE users.kodexuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.kodexuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3802 (class 0 OID 16444)
-- Dependencies: 204
-- Data for Name: kodexuser; Type: TABLE DATA; Schema: users; Owner: sgpostgres
--

INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (1, 'Brian', 'Brian Koser', '4812558', 'https://www.goodreads.com/user/show/4812558-brian-koser');
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (2, 'Melissa', 'Melissa Koser', '54340861', 'https://www.goodreads.com/user/show/54340861-melissa-koser');
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (3, 'Lydia', 'Lydia Koser', NULL, NULL);
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (4, 'Amber', 'Amber Koser', NULL, NULL);
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (5, 'Penny', 'Penelope Koser', NULL, NULL);


--
-- TOC entry 3811 (class 0 OID 0)
-- Dependencies: 203
-- Name: kodexuser_id_seq; Type: SEQUENCE SET; Schema: users; Owner: sgpostgres
--

SELECT pg_catalog.setval('users.kodexuser_id_seq', 1, false);


--
-- TOC entry 3670 (class 2606 OID 16451)
-- Name: kodexuser kodexuser_pkey; Type: CONSTRAINT; Schema: users; Owner: sgpostgres
--

ALTER TABLE ONLY users.kodexuser
    ADD CONSTRAINT kodexuser_pkey PRIMARY KEY (id);


--
-- TOC entry 3810 (class 0 OID 0)
-- Dependencies: 3808
-- Name: DATABASE postgres; Type: ACL; Schema: -; Owner: sgpostgres
--

REVOKE CONNECT,TEMPORARY ON DATABASE postgres FROM PUBLIC;
GRANT CONNECT ON DATABASE postgres TO sg_repl_user;
GRANT CONNECT ON DATABASE postgres TO sg_prm_user;


-- Completed on 2021-04-21 10:03:21

--
-- PostgreSQL database dump complete
--

