CREATE SCHEMA users;

CREATE TABLE users.kodexuser (
    id smallint NOT NULL,
    namedisplay character varying NOT NULL,
    namefull character varying NOT NULL,
    goodreadsuserid character varying,
    goodreadsurl character varying
);

ALTER TABLE users.kodexuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.kodexuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (1, 'Brian', 'Brian Koser', '4812558', 'https://www.goodreads.com/user/show/4812558-brian-koser');
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (2, 'Melissa', 'Melissa Koser', '54340861', 'https://www.goodreads.com/user/show/54340861-melissa-koser');
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (3, 'Lydia', 'Lydia Koser', NULL, NULL);
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (4, 'Amber', 'Amber Koser', NULL, NULL);
INSERT INTO users.kodexuser (id, namedisplay, namefull, goodreadsuserid, goodreadsurl) VALUES (5, 'Penny', 'Penelope Koser', NULL, NULL);

SELECT pg_catalog.setval('users.kodexuser_id_seq', 1, false);

ALTER TABLE ONLY users.kodexuser ADD CONSTRAINT kodexuser_pkey PRIMARY KEY (id);
